name: Prepare build environment
description: Common setup steps to run an Andlogview build job in the Linux container

runs:
  using: composite
  steps:
    - uses: gradle/wrapper-validation-action@v1
    - uses: actions/cache@v2
      name: Cached Gradle modules
      with:
        path: |
          /root/.gradle/caches/**
          /root/.gradle/wrapper/**
          !**.lock
          !**/gc.properties
        key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.*', 'buildSrc/**', '.github/actions/common-linux-setup/**') }}
        restore-keys: |
          ${{ runner.os }}-gradle6-cache-
    - run: test -e /root/.gradle/caches && find /root/.gradle/caches -type f -name '*.lock' -delete -o -name 'gc.properties' -delete || echo Skipped cleanup
      shell: bash
      name: Cleanup excessively cached stuff
