image: java:8

pipelines:
  branches:
    '{master,release/*}':  # SNAPSHOT builds for each checked-in pull request
      - step:
          caches:
            - gradle
            - gradlewrapper
          script:
            - bash ./gradlew build bitbucketUpload --continue
  pull-requests:
    '**':
      - step:
          caches:
            - gradle
            - gradlewrapper
          script:
            - bash tools/hooks/lint-all.sh
            - bash ./gradlew check --continue
          artifacts:
            - build/reports/**
definitions:
  caches:
    gradlewrapper: ~/.gradle/wrapper
