# Debian OpenJDK 8u302-b08
image: openjdk:8u302-jdk@sha256:e94c5b7f0f428b581053fbb8c0f994f1a27df570e0f7753fad6dffb06c3baf22

pipelines:
  pull-requests:
    '**':
      - step:
          caches:
            - gradle
            - gradlewrapper
          script:
            - export PYTHON_BINARY=python3
            - bash tools/hooks/lint-all.sh
            - bash ./gradlew check --continue
          artifacts:
            - build/reports/**
definitions:
  caches:
    gradlewrapper: ~/.gradle/wrapper
