name: PR Tests for Github
on:
  pull_request:
    branches:
      - master
      - release/*
jobs:
  run-precommit-tests:
    runs-on: ubuntu-latest
    container: openjdk:8u302-jdk@sha256:e94c5b7f0f428b581053fbb8c0f994f1a27df570e0f7753fad6dffb06c3baf22
    env:
      PYTHON_BINARY: python3
    steps:
      - uses: actions/checkout@v2
      - name: Set up environment
        uses: ./.github/actions/common-linux-setup
      - name: Run lint checks
        run: bash tools/hooks/lint-all.sh
      - name: Run unit tests
        # Do not use Gradle Daemon because we only have a single invocation and the running daemon interferes with the
        # caches.
        run: ./gradlew --no-daemon --continue --stacktrace check
      - name: Publish artifacts
        uses: ./.github/actions/publish-gradle-outputs
